[package]
name = "AdventureSmartCLI"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
calamine = "0.25.0"
toml = "0.8.19"
clap = { version = "4.5", features = ["derive"] }